In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import math
import matplotlib as mt
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, f1_score, recall_score
import seaborn as sns
import statistics
sns.set(style="whitegrid")
%matplotlib inline

In [4]:
dp = pd.read_csv("adult.csv")
df=dp.replace('?', np.NaN)
df = df.drop(['age'], axis = 1)
df = df.drop(['fnlwgt'], axis = 1)
df = df.drop(['capital.gain'], axis = 1)
df = df.drop(['capital.loss'], axis = 1)
df = df.drop(['hours.per.week'], axis = 1)
df

,workclass,education,education.num,marital.status,occupation,relationship,race,sex,native.country,income
0,NaN,HS-grad,9,Widowed,NaN,Not-in-family,White,Female,United-States,<=50K
1,Private,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,United-States,<=50K
2,NaN,Some-college,10,Widowed,NaN,Unmarried,Black,Female,United-States,<=50K
3,Private,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,United-States,<=50K
4,Private,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...
32556,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,United-States,<=50K
32557,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,United-States,<=50K
32558,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States,>50K
32559,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,United-States,<=50K
32560,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,United-States,<=50K

In [5]:
def weighted_entropy(data, col_num):
    entropies = []
    n_s = []
    entropy_of_attribute = entropy(data[:,col_num])
    for value in columns[col_num]:
        candidate_child = data[data[:,col_num] == value]
        n_s.append(len(candidate_child))
        entropies.append(entropy(candidate_child[:,6]))
    n_s = np.array(n_s)
    n_s = n_s / np.sum(n_s)
    weighted_entropy = n_s.dot(entropies)
    return weighted_entropy, entropy_of_attribute
    
def entropy(data):
    classes = np.unique(data)
    n = len(data)
    n_s = []
    for class_ in classes:
        n_s.append(len(data[data==class_]))
    n_s = np.array(n_s)
    n_s = n_s/n
    n_s = n_s * np.log2(n_s)
    return max(0,-np.sum(n_s))

In [8]:
def build_node(df, entropy, label, depth, class_="TBD", parent=None):
    new_node = dict()
    new_node['df'] = df
    new_node['entropy'] = entropy
    new_node['label'] = label
    new_node['depth'] = depth
    new_node['class'] = class_
    new_node['parent'] = parent
    new_node['children'] = []
    return new_node

root = build_node(df, entropy(df[:,6]), "all data", 0)
classes = np.unique(root['df'][:,6])
print(classes)

InvalidIndexError: (slice(None, None, None), 6)